image: Visual Studio 2015

environment:
    matrix:
        - TOOLSET: vs2010
        - TOOLSET: vs2012
        - TOOLSET: vs2013
        - TOOLSET: vs2015

build_script:
    - ps: Start-FileDownload 'https://github.com/bkaradzic/bx/raw/master/tools/bin/windows/genie.exe'
    - git submodule update --init
    - genie.exe %TOOLSET%
    - scripts\build_and_test.bat Debug Win32
    - scripts\build_and_test.bat Debug x64
    - scripts\build_and_test.bat Release Win32
    - scripts\build_and_test.bat Release x64
