image: Visual Studio 2015

environment:
    matrix:
        - TOOLSET: Visual Studio 10 2010
        - TOOLSET: Visual Studio 11 2012
        - TOOLSET: Visual Studio 12 2013
        - TOOLSET: Visual Studio 14 2015

build_script:
    - scripts\build_and_test.bat Debug
    - scripts\build_and_test.bat Release
    - if "%TOOLSET%" NEQ "Visual Studio 10 2010" scripts\build_and_test.bat Debug Win64
    - if "%TOOLSET%" NEQ "Visual Studio 10 2010" scripts\build_and_test.bat Release Win64
