language: cpp

sudo: required
dist: trusty

os:
    - linux
    - osx

env:
    - config=Debug cpu=i386
    - config=Debug cpu=x86_64
    - config=Release cpu=i386
    - config=Release cpu=x86_64

addons:
    apt:
        packages:
            - build-essential
            - gcc-multilib
            - g++-multilib

#before_install:
#    - "if [ ${TRAVIS_OS_NAME:-'linux'} = 'linux' ]; then scripts/before_install-linux.sh; fi"

script:
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=$config -DCMAKE_SYSTEM_PROCESSOR=$cpu ..
    - make VERBOSE=1
    - bin/sc_tests --reporter console
