language: cpp

sudo: required
dist: trusty

services:
    - docker

matrix:
    include:
        - os: linux
          env: arch=i386 config=Debug
        - os: linux
          env: arch=i386 config=Release

        - os: linux
          env: arch=x86_64 config=Debug
        - os: linux
          env: arch=x86_64 config=Release

        - os: linux
          env: arch=arm config=Debug
        - os: linux
          env: arch=arm config=Release

        - os: osx
          env: arch=i386 config=Debug
        - os: osx
          env: arch=i386 config=Release

        - os: osx
          env: arch=x86_64 config=Debug
        - os: osx
          env: arch=x86_64 config=Release

        - os: osx
          env: arch=universal config=Debug
        - os: osx
          env: arch=universal config=Release

addons:
    apt:
        packages:
            - build-essential
            - gcc-multilib
            - g++-multilib

script:
    - "scripts/build-${TRAVIS_OS_NAME}.sh"
