language: cpp

os:
    - linux
    - osx

env:
    - config=debug32
    - config=debug64
    - config=release32
    - config=release64

addons:
    apt:
        packages:
            - build-essential
            - gcc-multilib
            - g++-multilib

script:
    - git submodule update --init
    - scripts/build_and_test.sh "$TRAVIS_OS_NAME" "$config"
